Bug#38021787 Compile warning in gcs_xcom_networking.cc -Werror=attribute-warning
gcc 14 on EL9, RelWithDebInfo mode said:
error: call to '*__inet_ntop_chk' declared with attribute warning:
inet_ntop called with bigger length than size of destination buffer [-Werror=attribute-warning]

inet_ntop was called with incorrect 'size' argument.

Change-Id: I28410550394e2cd0d18ec30832a93af57496f422