Bug#38060707 compilation fails on EL7
router/src/jit_executor/src/database/result.cc:127:21: error: aggregate
'std::stringstream s' has incomplete type and cannot be defined
  127 |   std::stringstream s;
      |                     ^

Change
======

- include <sstream>
- use ostringstream instead of stringstream as that's the better,
  minimal type.

Change-Id: I3a9638caf1c81964bd3a829760c30e422ffff5e4