Bug#38193891 NotifyTest.NotificationSocketNotSet fails on windows
Running

  $ ./runtime_output_directory/Debug/routertest_component_sd_notify.exe

on windows fails:

  [ RUN      ] NotifyTest.NotificationSocketNotSet
  test_sd_notify.cc(1017): error:
  Expected equality of these values:
    0
    router.kill()
      Which is: -1073741502

(which is STATUS_CONTROL_C_EXIT) as the test stops the router before the
signal handler is installed.

Change
======

- wait for the signal handler to be installed.
- announce the signal-handler's readiness in the log on windows too

Change-Id: If484c930330f54d4fc8ffdff83c5753d2bffbfb9