BUG#38715858: New gtids library (WL #16076) does not build with Visual Studio 2019
MSVC 19.29 (VS16.11) gives two compilation errors in code introduced
in WL#16076:

- "libs\mysql\gtids\tag.h(83,75): error C2064: term does not evaluate
  to a function taking 1 arguments" and
  "libs\mysql\gtids\tag.h(83,75): message : 'transform': function
  declaration must be available as none of the arguments depend on a
  template parameter". I don't know why the compiler does not see that
  `transform` is callable, maybe a compiler bug. Fixed by making the
  class take a type argument instead of a non-type argument (which is
  also an ok way to implement the class).

- "binary '==': no global operator found which takes type
  'mysql::sets::Binary_operation' (or there is no acceptable
  conversion)": This looks like a compiler bug, it should know that
  operator== has built-in definitions for enum class types. Worked
  around by casting to int.

Change-Id: Idfb5eca674afd9d779c0bf23e689591c66f90083