Bug#37329260 libmysqlrouter_metadata_cache.so.1: cannot open shared object
When new MTR Router tests are run on pb2 they fail with the following error:

Error: Loading plugin for config-section '[metadata_cache:my_cluster]' failed:
libmysqlrouter_metadata_cache.so.1: cannot open shared object file: No such file or directory

Looking at the logs one can see that the relevant files layout is as follows:
usr/lib/mysqlrouter/private/libmysqlrouter_routing.so
usr/lib/mysqlrouter/private/libmysqlrouter_metadata_cache.so.1
usr/lib/mysqlrouter/plugin/metadata_cache.so

The install script does this to set up rpath:
-- Set runtime path of "../debian/tmp/usr/lib/mysqlrouter/plugin/metadata_cache.so" to
"/usr/lib/mysqlrouter/private/:$ORIGIN/private:/usr/lib/mysqlrouter/plugin/:$ORIGIN/
:/usr/lib/mysqlrouter/private:$ORIGIN/../lib/mysqlrouter/private/"
-- Set runtime path of "../debian/tmp/usr/bin/mysqlrouter" to
"/usr/lib/mysqlrouter/private/:$ORIGIN/private:/usr/lib/mysqlrouter/plugin/:$ORIGIN/
:/usr/lib/mysqlrouter/private:$ORIGIN/../lib/mysqlrouter/private/"

You can see there isn't a proper path being set from plugin to libs in private dir.

This patch uses the proper rpath setting that was already done but conditinally,
now it is always done for LINUX platform.

Change-Id: I128eb757733a35235801049387beb958ad5f074d
(cherry picked from commit cb9f081a816b2b7f0da3ab3f79cc5385deeeaafc)