Bug#38142283 Compile MySQL with clang 20 [allocator noclose]
Clang on Linux normally uses STL headers/libraries from gcc.  There is
evidently some mismatch of template instantiations, and build break
for the default CTOR ut::allocator::allocator().

include/c++/15/bits/hashtable_policy.h:1475:76: error:
chosen constructor is explicit in copy-initialization

ut0new.h:2200:12: note: explicit constructor declared here
 2200 |   explicit allocator(PSI_memory_key key = mem_key_std) : Allocator_base(key) {}

The actual problem is strict checking for explicit constructors during
copy initializations. We have two choices to fix it:

1- Make the allocator declarations explicit.
2- Create another non-explicit default constructor.

This patch implements alternative 2.

Note: There is no build break for clang when using -stdlib=libc++
but this is non-standard on Linux.

Change-Id: I02d81329ad5a61309b09d8fc1230b2b7ade8c20c
(cherry picked from commit f97007197c9f366136c2d27b093ee73fda0581e0)