WL#15440 MySQL REST Service (MRS) - Umbrella WL
Post-push fix for broken build with clang/Windows:

The global variable 'my_progname' to be EXPORTED from the shared
library mysqlrouter_mysqlclient.dll must be listed with its mangled
name, which is ?my_progname@@3PEBDEB

Also silence two warnings of the kind:
   error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
Both clang and gcc warns about this if we do
   cmake -DCMAKE_CXX_FLAGS="-Wzero-as-null-pointer-constant"
Visual Studio however rejects nullptr here error C2678:
binary '!=': no operator found which takes a left-hand operand of type 'nullptr'

And the standard says:
The behavior of a program that attempts to compare a strong_ordering
with anything other than the integer literal 0 is undefined.

Change-Id: Idc6dad0e32c4d916eb9123b90923b97563a58d08