Bug#38114704 Router fails to compile on MSVC 19.44.3520
The following error is seen:
error C2220: the following warning is treated as an error [C:\build\sb_1-20123200-1750808179.2897456\release\router\tests\mrs_client\mysqlrouter_mrs_client.vcxproj]

This patch adds missing throw for the exception that was meant to be
thrown.

Change-Id: I7a1fb1067bb49b1f42de939dc7843f2178412556