Bug#36716069 Compile MySQL with GCC 15 [noclose]
Prefer snprintf() over strncpy():

ssl_acceptor_context_iterator.cc:130:10:
/usr/include/bits/string_fortified.h:100:34: error:
'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]

Change-Id: I3af700e545590998ee3041e86f92d67a294a76fb
(cherry picked from commit 6fdf3410c681e94ea876598559ae1346e39b1ad5)