Bug#37385923 routertest_integration_routing_sharing select_overlong times out
Post-push fix for broken windows build:
error C2672: 'std::min': no matching overloaded function found

std::min(sz, 16UL * 1024); is rejected on Win
std::min(sz, 16ULL * 1024); is rejected on macOS

so we must static_cast it to size_t;

Change-Id: I2ab832fe2cb011de9e0a05098638c3b7aad0da8a