Bug#37702396 Upgrade to GCC 14 on RHEL9 [xplugin noclose]
On Oracle Linux 9 we currently build with /opt/rh/gcc-toolset-13
Upgrade to /opt/rh/gcc-toolset-14

Fix warning:
plugin/x/src/ngs/error_code.h:68:17: error:
'MEM[(const struct Error_code &)_17].error' may be used uninitialized [-Werror=maybe-uninitialized]
   68 |       error = o.error;
      |               ~~^~~~~

Change-Id: I90e4aacceda52976c2df95b8d66a280682abfad1