Bug#37458343 Fix warnings from PGO/LTO build [cmake,noclose]
When building with LTO at the -fprofile-use phase, we get extra warnings.
Fix them, or silence them, or downgrade from error to warning.

This patch was developed on el9 using gcc 13.3.1

Remove DOWNGRADE_STRINGOP_WARNINGS for components,
do it in MYSQL_ADD_COMPONENT() instead.

Add some DISABLE_MISSING_PROFILE_WARNING for things that are not part
of 'run-profile-suite'.

dd_string_type-t.cc:104:24: error:
argument 1 value 9223372036854775808 exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]

payload_event_buffer_istream-t.cc:119:16:
/usr/include/bits/string_fortified.h:59:33: error:
memset specified bound 18446744073709551597 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

Change-Id: I5f2ea05a7b90f5cdb946b3e6db3915d16bc1917b
(cherry picked from commit c6795468b273838a3c88bf79c92db3d8b355c425)