Bug#34638573 Compile MySQL with clang 15 [noclose]
We need to construct 'struct Ssl_context::Config' explicitly in the call to
std::make_unique<Config>. Older clang versions said:

plugin/x/src/ssl_context.cc:67:7: error: no matching function for call to 'make_unique'
      std::make_unique<Config>({tls_version, ssl_key, ssl_ca, ssl_capath,

This is a followup to
    Bug#37471922: Auto-fix clang-tidy warnings [35/n] [noclose]
    This commit fixes the warning 'modernize-make-unique'.

Change-Id: Ic7bb1266f0e9723cc705e86d0e263f48790d2a81